### PR TITLE
Fixes #78 - unwrap command wrapper when it contains a $query key

### LINKED ISSUE #78: Commands with non-primary ReadPreference need to be unwrapped
When the driver executes a command using a non-primary ReadPreference, it will wrap the query to look like this:
```
{ $query: <the query>, $readPreference: <the ReadPreference> }
```

Since the message is `OP_QUERY` and the collection name ends with `$cmd`, mongo-java-server interprets the query as a command and expects the command type (`find`, `insert`, `update`, etc.) to exist as the first key in the query Document.

When the non-primary ReadPreference scenario occurs (when the `$query` key is present), `MongoDatabaseHandler` should extract the `$query` Document from the query object rather than passing the query object directly.

An example:
```
// this fails:
final MongoClient mongoClient = new MongoClient(new ServerAddress(mongoServer.getLocalAddress()), MongoClientOptions.builder().readPreference(ReadPreference.nearest()).build());
mongoClient.getDatabase("testdb").getCollection("coll").countDocuments();


// this succeeds:
final MongoClient mongoClient = new MongoClient(new ServerAddress(mongoServer.getLocalAddress()), MongoClientOptions.builder().readPreference(ReadPreference.primary()).build());
mongoClient.getDatabase("testdb").getCollection("coll").countDocuments();
```

This was tested with mongo-java-driver 3.10.1. I believe this covers the issues brought up in #66 and #77.

### PR DESCRIPTION
**Pull request by bfink13**

### CODE REVIEW

File: test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java [hunk 1]
```diff
@@ -250,6 +251,11 @@ public void testCountCommand() {
         assertThat(collection.count()).isZero();
     }
 
+    @Test
+    public void testNonPrimaryCountCommand() {
+        assertThat(collection.withReadPreference(ReadPreference.nearest()).countDocuments()).isZero();
```
Comment (bfink13) [inline test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java]: this gets the job done but isn't exactly descriptive. any recommendations for where else this change could be tested?

Comment (bwaldvogel) [reply test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java]: What do you think about having two tests?
You could keep that test since a query with read preference was not yet covered.
However, the Java driver implementation could change anytime and thus it doesn’t guarantee to test what you want to test. So I would suggest to add another test where you construct a `$query` object explicitly?

Comment (bfink13) [reply test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java]: That seems like a good idea to me.

File: core/src/main/java/de/bwaldvogel/mongo/wire/MongoDatabaseHandler.java [hunk 2]
```diff
@@ -129,7 +129,7 @@ private MongoReply queryFailure(MessageHeader header, MongoServerException excep
         return new MongoReply(header, obj, ReplyFlag.QUERY_FAILURE);
     }
 
-    private Document handleCommand(Channel channel, MongoQuery query) {
+    Document handleCommand(Channel channel, MongoQuery query) {
```
Comment (bfink13) [inline core/src/main/java/de/bwaldvogel/mongo/wire/MongoDatabaseHandler.java]: this seem ok to you? i have zero experience with testing Netty applications - it didn't appear there was a real clear way to wire up `Channel`s and `ChannelHandlerContext`s

**Comment by bfink13** [comment]
@bwaldvogel any other thoughts on this?

File: core/src/main/java/de/bwaldvogel/mongo/wire/MongoDatabaseHandler.java (hunk 2 above)
Comment (bwaldvogel) [reply core/src/main/java/de/bwaldvogel/mongo/wire/MongoDatabaseHandler.java]: I was hoping we could formulate it as case in `AbstractBackendTest`… I just tried by myself and failed. So I will merge the PR for now. If we find a better solution to test it, we can improve it anytime.

**Comment by bwaldvogel** [comment]
Thanks for your contribution!
