### PR TITLE
#62 Allow _id to be set when the operation is an upsert

### LINKED ISSUE #62: _id field should be modifiable during upserts
During an update, `AbstractMongoCollection` will throw an exception if the `_id` field is being set. However, if the update is actually an upsert, the `_id` field should be allowed to be set via the update query.

Documentation for specifically `$setOnInsert`: https://jira.mongodb.org/browse/SERVER-9958

### PR DESCRIPTION
**Pull request by bfink13**
Fixes #62

### CODE REVIEW

File: core/src/test/java/de/bwaldvogel/mongo/backend/AbstractMongoCollectionTest.java [hunk 1]
```diff
@@ -48,10 +69,11 @@ protected Object findDocumentPosition(Document document) {
             throw new UnsupportedOperationException();
         }
 
+        // todo: actually enforce all the parameters
```
Comment (bfink13) [inline core/src/test/java/de/bwaldvogel/mongo/backend/AbstractMongoCollectionTest.java]: I realize this isn't the absolute greatest solution, but it works for the tests that are here so far. I figured it can be updated once tests are added that actually make use of these parameters.

**Comment by bfink13** [comment]
FYI I had to pin netty versions to `4.1.34.Final` to get this to work locally - is that expected?

**Comment by bwaldvogel** [comment]
Thanks for your contribution!

> FYI I had to pin netty versions to 4.1.34.Final to get this to work locally - is that expected?

No, that’s unexpected. Can you explain the problem in more detail and what you needed to do to fix it?

**Comment by bfink13** [comment]
When I used `gradle publishToMavenLocal` the `core` module resolved all of its `netty` dependencies to `5.0.0.Alpha2` presumably because that's the latest version in Maven (and the dependencies call for `latest.release`). I don't remember the exact error now, but it was something along the lines of ClassNotFound/MethodNotFound.

After pinning those dependencies to `4.1.34.Final` everything worked as expected. I didn't include that in this PR because it seemed to be working for you since all the published versions of `mongo-java-server` pull `4.1.34.Final` ¯\\\_(ツ)_/¯

**Comment by bwaldvogel** [comment]
Hm, version `5.0.0.Alpha2` shouldn’t have been pulled because the version _is_ actually pinned to `4.1.34.Final` via Gradle’s [dependency locking mechanism](https://docs.gradle.org/current/userguide/dependency_locking.html).

Did you literally use `gradle publishToMavenLocal` instead of `./gradlew publishToMavenLocal`?

**Comment by bfink13** [comment]
Ahhhh yes yes....`./gradlew publishToMavenLocal` did the trick. Sorry about that.

**Comment by bwaldvogel** [comment]
No problem. Glad to hear that we found the problem :)

**Comment by bfink13** [comment]
Do you have a standard release cadence or have an estimate for when this will be released? Just trying to give an estimate to one of our internal teams - we're switching them from fongo.

**Comment by bwaldvogel** [comment]
In the last months I’ve usually released a new version about once or twice per month.

I guess we could publish the next version early this week, as soon as I got feedback for #60.

**Comment by bfink13** [comment]
Sounds good, no rush.
