### PR TITLE
Issue 64

### LINKED ISSUE #64: Removing non-existent intermediate sub-key should not throw an exception
The current behavior for removing a sub-key is this:
```
Object subObject = getFieldValueListSafe(document, mainKey);
if (subObject instanceof Document || subObject instanceof List<?>) {
   return removeSubdocumentValue(subObject, subKey, matchPos);
} else {
   throw new MongoServerException("failed to remove subdocument");
}
```
With the code above, if an intermediate sub-key is missing, an exception will be thrown. It is perfectly reasonable that an intermediate sub-key does not exist on the document in question. If it doesn't, the operation (remove or rename) should be ignored for that document.

### PR DESCRIPTION
**Pull request by bfink13**
Fixes #64.

Several changes in this one:
- During a rename, if the source key does not exist, don't do anything
- During key removal, if the key doesn't exist, treat the value as missing rather than null
- During key removal, if the key references an array and the key is not a number, treat the value as missing rather than throwing an exception
- During key removal while traversing subdocuments, if a value exists for the current level but it is not a Document or a List, treat it as missing
- During key removal while traversing subdocuments, if the current key references a subvalue that doesn't exist, treat it as missing
- If a rename is happening, verify that the source document we're renaming is valid (not part of an array)

### CODE REVIEW

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java [hunk 1]
```diff
@@ -452,4 +465,8 @@ static Document cursorResponse(String ns, List<Document> firstBatch) {
         markOkay(response);
         return response;
     }
+
+    static boolean isNullOrEmpty(String str) {
```
Comment (bfink13) [inline core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: i couldn't find an existing version of this anywhere. let me know if i missed one

**Comment by bfink13** [comment]
Whoops, looks like one test variant isn't happy...

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java [hunk 2]
```diff
@@ -260,6 +260,24 @@ static boolean hasSubdocumentValue(Object document, String key) {
         }
     }
 
+    static boolean canFullyTraverseSubkeyForRename(Object document, String key) {
```
Comment (bfink13) [inline core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: I don't entirely love needing this, but it seems renames are a little special. If you have alternative ideas, I'm all ears.

File: test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java [hunk 3]
```diff
@@ -3088,6 +3094,31 @@ public void testRenameField() throws Exception {
...
+        collection.updateOne(json("_id: 1"), json("$rename: {'foo.z': 'foo.a', 'bar.a': 'bar.b'}"));
+        assertThat(collection.find().first()).isEqualTo(json("_id: 1, foo: { a: 1, b: 2 }, bar: { x: 3, d: 4 }}"));
+
+        collection.updateOne(json("_id: 1"), json("$rename: {'missing.a': 'missing.b'}"));
+        assertThat(collection.find().first()).isEqualTo(json("_id: 1, foo: { a: 1, b: 2 }, bar: { x: 3, d: 4 }}"));
+
+        collection.updateOne(json("_id: 1"), json("$rename: {'foo.a': 'a', 'bar.x': 'bar.c'}"));
+        assertThat(collection.find().first()).isEqualTo(json("_id: 1, foo: { b: 2 }, bar: { c: 3, d: 4 }, a: 1}"));
+
+        assertThatExceptionOfType(Exception.class).isThrownBy(
```
Comment (bfink13) [inline test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java]: Is there a better way to do this? Constructing a full error message for a MongoServerError is insanely difficult for this particular case.

Comment (bwaldvogel) [reply test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java]: We should at least make sure the right kind of exception is thrown.
If you expect an exception of type `Exception`, it could even be something like a `NullPointerException` that shouldn’t be thrown here.

File: core/src/main/java/de/bwaldvogel/mongo/backend/FieldUpdates.java [hunk 4]
```diff
@@ -343,8 +343,15 @@ private void handleRename(String key, Object toField) {
 
     private void applyRenames() {
         for (Entry<String, String> entry : renames.entrySet()) {
+            if (!Utils.canFullyTraverseSubkeyForRename(document, entry.getKey())) {
+                throw new MongoServerException("cannot traverse element");
```
Comment (bwaldvogel) [inline core/src/main/java/de/bwaldvogel/mongo/backend/FieldUpdates.java]: I think to be closer to real MongoDB we should rather throw an `PathNotViableException` here
```suggestion
                throw new PathNotViableException("cannot traverse element");
```

File: core/src/main/java/de/bwaldvogel/mongo/backend/FieldUpdates.java [hunk 5]
```diff
@@ -343,8 +343,15 @@ private void handleRename(String key, Object toField) {
...
+            }
+
             Object value = Utils.removeSubdocumentValue(document, entry.getKey(), matchPos);
-            changeSubdocumentValue(document, entry.getValue(), value);
+
+            if (value != Missing.getInstance()) {
```
Comment (bwaldvogel) [inline core/src/main/java/de/bwaldvogel/mongo/backend/FieldUpdates.java]:
```suggestion
            if (!(value instanceof Missing)) {
```

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java [hunk 6]
```diff
@@ -260,6 +260,24 @@ static boolean hasSubdocumentValue(Object document, String key) {
...
+        int dotPos = key.indexOf('.');
+        if (dotPos > 0) {
+            String mainKey = key.substring(0, dotPos);
+            String subKey = getSubkey(key, dotPos, new AtomicReference<>());
+            Object subObject = Utils.getFieldValueListSafe(document, mainKey);
+            if (subObject instanceof Document) {
+                return canFullyTraverseSubkeyForRename(subObject, subKey);
+            } else if (subObject == Missing.getInstance()) {
```
Comment (bwaldvogel) [inline core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]:
```suggestion
            } else if (subObject instanceof Missing) {
```

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java (hunk 2 above)
Comment (bwaldvogel) [reply core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: I don’t have a good idea either at the moment. Lets keep it like that. We can refactor it at any time and this looks like a clear improvement!

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java [hunk 7]
```diff
@@ -393,6 +402,10 @@ private static Object removeSubdocumentValue(Object document, String key, Atomic
             Object subObject = getFieldValueListSafe(document, mainKey);
             if (subObject instanceof Document || subObject instanceof List<?>) {
                 return removeSubdocumentValue(subObject, subKey, matchPos);
+            } else if (!isNullOrEmpty(subKey)) { // not missing, but not a Document or List, so no subdocuments
```
Comment (bwaldvogel) [inline core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: I’m wondering if an empty subKey can even occur here…

Maybe we should simplify this if-else cascade to something like:
```java
            if (subObject instanceof Document || subObject instanceof List<?>) {
                return removeSubdocumentValue(subObject, subKey, matchPos);
            } else {
                return Missing.getInstance();
            }
```

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java (hunk 1 above)
Comment (bwaldvogel) [reply core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: Right, it doesn’t exist yet. But we probably don’t need it (see comment above)

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java (hunk 7 above)
Comment (bfink13) [reply core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: Yea, I thought about the same thing. However, that's drawing an implicit dependency that `getSubKey` will always do the right thing (return a subkey when a dot exists in the key). I figured it would be better to throw an exception if somehow `getSubKey` didn't do the right thing.

Thoughts?

(regardless, i'll change `subObject == Missing.getInstance()` to `subObject instanceof Missing`)

File: test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java (hunk 3 above)
Comment (bfink13) [reply test-common/src/main/java/de/bwaldvogel/mongo/backend/AbstractBackendTest.java]: Changed this to `MongoWriteException`

**Comment by bfink13** [comment]
Looks like java 11 build hiccuped because it couldn't download the jdk. Are you able to re-run it?

**Comment by bwaldvogel** [comment]
> Are you able to re-run it?

Unfortunately I looks like it’s not just a temporary hiccup but a more permanent build problem on JDK11. My own builds failed as well.

File: core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java (hunk 7 above)
Comment (bwaldvogel) [reply core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: Ok, good thoughts.

What do you think about adding an assertion (e.g. `Assert.isTrue(…)`) which makes sure that we would notice if `getSubKey` would change the behaviour in an unexpected/incompatible way?

Comment (bfink13) [reply core/src/main/java/de/bwaldvogel/mongo/backend/Utils.java]: Ah sure, that's probably better.
